### ISSUE TITLE
Plugin to reset Parameters in a Profile

### ISSUE THREAD

**Issue by 5axes** [fieldOfView/Cura-PluginsMeta#14]
There are often requests for the possibility of defining, for example, a flow rate in the material definition (via your Material plugin). The problem is that the custom profile settings overwrite this data.  The only solution I know is to edit the profile manualy via a text editor and delete the unnecessary parameter. 
The idea would be to have a Plugin that would allow to delete in the active profile some parameters already defined. We could for example have the list of parameters available in Cura, show those with a value in the active profile and by unchecking the box we would delet this parameter.

![image](https://user-images.githubusercontent.com/11015345/176607036-515c02e7-20fb-48ba-b6ef-3d4cb830b511.png)

**Comment by 5axes** [comment]
Ok I can close this point : https://github.com/5axes/ProfilePlus

**Comment by fieldOfView** [comment]
Please stop doing this, you are annoying me.

**Comment by 5axes** [comment]
? 
I'm sorry, that was not my goal, even if I don't understand the problem exactly: Open a new issue. Or open a new issue and finally see if I can handle it on my side ?

**Comment by fieldOfView** [comment]
What annoys me is that you put up an issue here (ie: you ask me to create something), and then do it yourself. That is a waste of your and my energy. The only thing that it accomplishes is that I stop reading your posts, because I know you are probably going to do it yourself anyway.

Of course I don't mind you creating plugins; I applaud it, and I admire your enthusiasm. But I have told you before you don't have to announce what you are going to do yourself with a post on my todo list. Feel free to create a todo list of your own.
