### ISSUE TITLE
Tab helper disk

### ISSUE THREAD

**Issue by 5axes** [fieldOfView/Cura-PluginsMeta#6]
Plugin to add rounded Tab as solution to reduce the warping effect. 
![vue_plugin](https://user-images.githubusercontent.com/11015345/82690318-45c9d180-9c5c-11ea-94cb-a4d4ca2c0a0e.jpg)
Using Helper Disks, which act on the corners of your model to help keep everything pinned down. Once the print is finished, the disks can be cut away pretty easily.

**Comment by 5axes** [comment]
first test ...
[TabAntiWarping](https://github.com/5axes/TabAntiWarping)

**Comment by fieldOfView** [comment]
Thanks for your enthusiasm about creating plugins. 

If you are going to create the plugin yourself, there is no need to request it here.

Please note that I am an external contributor like you. This repository is not a general place to request plugins for Cura, but it is a place for me to collect requests I get in other places. It will generally only be seen by me. I appreciate your ideas, and feel free to post them here, but I already have a lot of plugins to maintain.

I am closing this, because you seem to have a working implementation of it already.
